### PR TITLE
Replaced Facebook with LinkedIn

### PR DESCRIPTION
**Pull request by Red-0111**

### CODE REVIEW

**Comment by ritikrajdev** [comment]
Hey @Red-0111 Can you please delete the facebook logo too from the directories. We no longer need it.

**Comment by Red-0111** [comment]
Alright!

**Comment by Red-0111** [comment]
Done @ritikrajdev sir please have a look

**Comment by ritikrajdev** [comment]
Sorry for the delay will review it within an hour.
Thanks for the contribution :wink:

**Pull request merged**
